language: node_js
node_js:
  - '8'
notifications:
  email: false
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=test
install:
  - npm i
script:
  - npm test
after_success:
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper.*$/
