language: node_js
node_js:
  - '8'
notifications:
  email: false
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=test
before_install:
  - rm .npmrc
  - 'echo "//registry.npmjs.org/:_authToken="${NPM_TOKEN} > .npmrc'
install:
  - npm i
script:
  - npm test
after_success:
  - npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper.*$/
