service: serverless-2
provider:
  name: google
  runtime: nodejs
  project: serverless-demo-203010
  credentials: keyfile.json
plugins:
  - serverless-google-cloudfunctions
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
functions:
  first:
    handler: http
    events:
      - http: path
